version: '3'

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    ports:
      - 3333:3333
    volumes:
      - ./server:/home/node/app
    depends_on:
      - redis
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
     